/*
	R3 Auto Map Gen.
	database.js
	
	Original database was imported from R3V2 / R3V3

	name: 			String 		Map Name
	location: 		String		Map location
	canSave: 		Boolean		Player can save
	haveItemBox: 	Boolean 	Map have icon box
	gameStart: 		Boolean 	Map where game starts
	gameEnd: 		Boolean 	Map where game ends
*/

temp_DATABASE = {

	// BioHazard
	bio1: {
		bioRandObjectives: {},
		rdt: {
			'0000': {name: 'Unknown Map', location: 'Unknown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R100': {name: 'Save Room', location: 'Mansion 1F', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R101': {name: '1F Left Stairs', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R102': {name: 'Vacant Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R103': {name: 'F Passage', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R104': {name: 'Tea Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R105': {name: 'Dining Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R106': {name: 'Main Hall', location: 'Mansion 1F', haveItemBox: !1, canSave: !0, gameStart: !0, gameEnd: !1},
			'R107': {name: 'Gallery', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R108': {name: 'L Passage', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R109': {name: 'Trap Passage', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10A': {name: 'Back Passage', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10B': {name: '1F Right Stairs', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10C': {name: 'Green House', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10D': {name: 'Tiger Statue Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10E': {name: 'Employee Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10F': {name: 'Bar (Piano Puzzle)', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R110': {name: '1F Elevator', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R111': {name: 'Dressing Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R112': {name: 'Wardrobe Mirror', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R113': {name: 'Bathroom', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R114': {name: 'Boiler', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R115': {name: 'Ceiling Trap (Sandwitch)', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R116': {name: 'Living Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R117': {name: 'Large Gallery', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R118': {name: 'Room under stairs', location: 'Mansion 1F', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R119': {name: 'Study', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11A': {name: 'Roofed Passage', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11B': {name: 'Store Room', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11C': {name: 'Wardrobe Closet', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R200': {name: '1F --> B1 Elevator', location: 'Mansion 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R201': {name: '2F Left Stairs', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R202': {name: 'Dining Room 2F', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R203': {name: 'Mansion Hall 2F', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R204': {name: '2F Red Corridor', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R205': {name: 'Armor Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R206': {name: 'Botany Book (Doll) Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R207': {name: '2F Right Stairs', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R208': {name: 'Deer Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R209': {name: 'Bedroom', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20A': {name: 'Study Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20B': {name: 'Front Lesson Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20C': {name: 'Lesson Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20D': {name: 'Pillar Passage', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20E': {name: 'Front Of Attic', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20F': {name: 'Candle Dinner Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R210': {name: 'Attic (Snake Fight)', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R211': {name: 'Terrace Passage', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R212': {name: 'Terrace (Forest)', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R213': {name: 'Front Elevator', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R214': {name: 'Routh Passage', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R215': {name: 'Stuffed Room', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R216': {name: 'Library A', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R217': {name: 'Library B', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R218': {name: 'Hidden Library', location: 'Mansion 2F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R219': {name: 'Shed', location: 'Mansion B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R21A': {name: 'Under Passage', location: 'Mansion B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R21B': {name: 'Under Passage 2', location: 'Mansion B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R21C': {name: 'B1 Kitchen', location: 'Mansion B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R300': {name: 'First House Out', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R301': {name: 'Water Gate', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R302': {name: 'Waterfall', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R303': {name: 'Heliport', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !0},
			'R304': {name: 'Second House Gate', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R305': {name: 'Fountain', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R306': {name: 'Item Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R307': {name: 'Ladder Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R308': {name: 'Branch Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R309': {name: 'Darkness Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30A': {name: 'Enrico Room', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30B': {name: 'Rock Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30C': {name: 'Black Tiger Room', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30D': {name: 'Straight Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30E': {name: 'Coutyard B1 Save Room', location: 'Coutyard B1', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R30F': {name: 'Crank Passage', location: 'Coutyard B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R310': {name: 'Coutyard to Laboratory', location: 'Coutyard 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R400': {name: 'Guardhouse Entrance', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R401': {name: 'Room 001', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R402': {name: 'Room 001 - Bathroom', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R403': {name: 'Guardhouse Save Room', location: 'Guardhouse 1F', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R404': {name: 'Guardhouse Bar', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R405': {name: 'Center Passage', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R406': {name: 'Room 002', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R407': {name: 'Room 002 - Bathroom', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R408': {name: 'Honeycomb Passage', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R409': {name: 'Drug Storehouse', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40A': {name: 'Room 003', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40B': {name: 'Room 003 - Bathroom', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40C': {name: 'Guardhouse Plant Boss', location: 'Guardhouse 1F', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40D': {name: 'Under Passage', location: 'Guardhouse B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40E': {name: 'Water Tank', location: 'Guardhouse B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40F': {name: 'Security Room', location: 'Guardhouse B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R410': {name: 'Arms. Storehouse', location: 'Guardhouse B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R411': {name: 'Control Room', location: 'Guardhouse B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R500': {name: 'Under Fountain', location: 'Laboratory B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R501': {name: 'Heliport Passage', location: 'Laboratory B1', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R502': {name: 'Ladder Room', location: 'Laboratory B2', haveItemBox: !0, canSave: !1, gameStart: !1, gameEnd: !1},
			'R503': {name: 'Lab Stairs', location: 'Laboratory B2', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R504': {name: 'Conference Room', location: 'Laboratory B2', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R505': {name: '\"O\" Passage', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R506': {name: 'Small Laboratory', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R507': {name: 'Lab Mortuary', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R508': {name: '\"MO Disk\" Corridor', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R509': {name: 'Private Room A', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50A': {name: 'Private Room B', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50B': {name: 'Cell Corridor', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50C': {name: 'Elevator Hallway', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50D': {name: 'Escape Elevator', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50E': {name: 'Lab Save Room', location: 'Laboratory B3', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R50F': {name: 'Maze A', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R510': {name: 'Maze B', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R511': {name: 'Engine Room', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R512': {name: 'Cell Room', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R513': {name: 'Tyrant Room', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R514': {name: 'Front of Tyrant', location: 'Laboratory B3', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R515': {name: 'B4 Elevator', location: 'Laboratory B3 / B4', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1}
		}
	},

	// BioHazard 2
	bio2: {
		bioRandObjectives: {},
		rdt: {
			'0000': {name: 'Unknown Map', location: 'Unknown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
		}
	},

	// BioHazard 3 - Last Escape
	bio3: {

		// BioRand Objectives
		bioRandObjectives: {
			'R20C': {endsOn: 'R215', applyDistance: !0},
			'R30C': {endsOn: 'R30D', applyDistance: !0},
			'R30D': {endsOn: null, applyDistance: !0},
			'R415': {endsOn: null, applyDistance: !0},
			'R50C': {endsOn: 'R50D', applyDistance: !0},
			'R50D': {endsOn: 'R50F', applyDistance: !1}
		},

		// Map list
		rdt: {
			'0000': {name: 'Unknown Map', location: 'Unknown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R100': {name: 'Warehouse Save Room', location: 'Uptown', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R101': {name: 'Warehouse', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R102': {name: 'Warehouse Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R103': {name: 'Warehouse Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R104': {name: 'Basement Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R105': {name: 'Bar Jack Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R106': {name: 'Boutique Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R107': {name: 'Bar Jack', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R108': {name: 'Barricade Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R109': {name: 'Hydrant Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10A': {name: 'Main Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10B': {name: 'Sales Office Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10C': {name: 'Hydrant Alley (Save)', location: 'Uptown', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R10D': {name: 'Jill\'s Apartment', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !0, gameEnd: !1},
			'R10E': {name: 'Back Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R10F': {name: 'Boutique', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R110': {name: 'R.P.D. Gate', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R111': {name: 'R.P.D. Main Hall', location: 'Police Station', haveItemBox: !1, canSave: !0, gameStart: !1, gameEnd: !1},
			'R112': {name: 'R.P.D. Office', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R113': {name: 'Files Room', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R114': {name: 'Corridor with ladder', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R115': {name: 'Corridor', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R116': {name: 'Press conference Room', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R117': {name: 'Dark Room', location: 'Police Station', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R118': {name: '2F Corridor', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R119': {name: 'Corridor to S.T.A.R.S. Room', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11A': {name: 'S.T.A.R.S. Room', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11B': {name: 'Sales Office', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11C': {name: 'Sales Office Storeroom', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11D': {name: 'Warehouse Alley (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11E': {name: 'Warehouse Street (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R11F': {name: 'Basement Alley (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R120': {name: 'Bar Jack Alley (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R121': {name: 'Boutique Street (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R122': {name: 'Barricade Alley (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R123': {name: 'Hydrant Alley (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R124': {name: 'Main Street (Night)', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R125': {name: 'R.P.D. Gates (Night)', location: 'Police Station', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R200': {name: 'Bus Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R201': {name: 'Mechanic Parking Lot', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R202': {name: 'Parking Lot Back', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R203': {name: 'Construction Site', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R204': {name: 'Energy Station Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R205': {name: 'Grill 13 Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R206': {name: 'Shopping Dist.', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R207': {name: 'Raccon City Hall Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R208': {name: 'Raccon City Hall', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R209': {name: 'Party Party Alley', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20A': {name: 'Giant Worm Alley', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20B': {name: 'Trolley Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20C': {name: 'Trolley', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20D': {name: 'Stagla Gas Station', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20E': {name: 'Stagla Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R20F': {name: 'Press (2F)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R210': {name: 'Press (1F)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R211': {name: 'Grill 13 (1F)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R212': {name: 'Grill 13 (B1)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R213': {name: 'Energy Station Entrance', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R214': {name: 'Energy Station', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R215': {name: 'Trolley (Running)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R216': {name: 'Shopping Dist. Save Room', location: 'Downtown', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R217': {name: 'Stagla Street (After)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R218': {name: 'Fire Hose Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R219': {name: 'Press (1F)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R21A': {name: 'Parasite Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R21B': {name: 'Mechanic\'s Office', location: 'Downtown', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R300': {name: 'Chapel', location: 'Clock Tower', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R301': {name: 'Piano Hall', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R302': {name: 'Dinner Room', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R303': {name: 'Clock Tower Garden', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R304': {name: 'Main Hall (1F)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R305': {name: 'Resting Room', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R306': {name: 'Living Room', location: 'Clock Tower', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R307': {name: 'Clock Tower Library', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R308': {name: 'Corridor to Clock Puzzle', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R309': {name: 'Clock Puzzle', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30A': {name: 'Main Hall (2F)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30B': {name: 'Tower Balcony', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30C': {name: 'Machinery Room', location: 'Clock Tower', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R30D': {name: 'Clock Tower Nemesis Fight', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30E': {name: 'Main Hall Destroyed', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R30F': {name: 'Piano Hall & Dinner Room', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R310': {name: 'Chapel (Carlos)', location: 'Clock Tower', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R311': {name: 'Resting Room (Carlos)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R312': {name: 'Living Room (Carlos)', location: 'Clock Tower', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R313': {name: 'Clock Tower Library (Carlos)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R314': {name: 'Corridor to Clock Puzzle (Carlos)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R315': {name: 'Clock Puzzle (Carlos)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R316': {name: 'Main Hall Destroyed (Carlos)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R317': {name: 'Piano Hall & Dinner Room (Carlos)', location: 'Clock Tower', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R400': {name: 'Hospital Street Destroyed', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R401': {name: 'Park Office', location: 'Park', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R402': {name: 'Hospital Entrance', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R403': {name: 'Hospital Office', location: 'Hospital', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R404': {name: 'Waiting Room', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R405': {name: 'Corridor (4F)', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R406': {name: 'Room 402', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R407': {name: 'Room 401', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R408': {name: 'Data Room', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R409': {name: 'Corridor (B3)', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40A': {name: 'Laboratory 1', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40B': {name: 'Laboratory 2', location: 'Hospital', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40C': {name: 'Park Entrance', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40D': {name: 'Water Pump Puzzle', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40E': {name: 'Park \"L\" Bridge', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R40F': {name: 'Park Exit', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R410': {name: 'Sewer Passage', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R411': {name: 'Graveyard', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R412': {name: 'Park Warehouse', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R413': {name: 'Park Warehouse Save Room', location: 'Park', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R414': {name: 'Park Secret Room', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R415': {name: 'Park Graveyard (Worm)', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R416': {name: '[UNUSED] Copy of R510 (Bridge)', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R417': {name: 'Park Street', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R500': {name: 'Factory Entrance', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R501': {name: 'Resting Room', location: 'Dead Factory', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R502': {name: 'Steam Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R503': {name: 'Control Room (1F)', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R504': {name: 'Corridor to Monitor Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R505': {name: 'Monitor Room', location: 'Dead Factory', haveItemBox: !0, canSave: !0, gameStart: !1, gameEnd: !1},
			'R506': {name: 'Water Sample Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R507': {name: 'Control Room (B1)', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R508': {name: 'Corridor to Disposal Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R509': {name: 'Disposal Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50A': {name: 'Communication Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50B': {name: 'Corridor to Car Cemetery', location: 'Dead Factory', haveItemBox: !0, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50C': {name: 'Car Cemetery', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50D': {name: 'Incinerator Room', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R50E': {name: 'Extraction Point', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !0},
			'R50F': {name: 'Elevator to Extraction Point', location: 'Dead Factory', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R510': {name: 'Bridge to Dead Factory', location: 'Park', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			
			/*
				Mercs. Maps
			*/
			'R600': {name: '(Merc) Warehouse Save Room', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !0},
			'R601': {name: '(Merc) Warehouse', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R607': {name: '(Merc) Bar Jack', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R60B': {name: '(Merc) Pharmacy Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R60E': {name: '(Merc) Back Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R60F': {name: '(Merc) Unknown Location', location: 'Unknown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R61B': {name: '(Merc) Pharmacy', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R61C': {name: '(Merc) Pharmacy Product Stock', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R61D': {name: '(Merc) Warehouse Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R61E': {name: '(Merc) Warehouse Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R61F': {name: '(Merc) Basement Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R620': {name: '(Merc) Bar Jack Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R621': {name: '(Merc) Boutique Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R622': {name: '(Merc) Barricade Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R623': {name: '(Merc) Hydrant Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R624': {name: '(Merc) Main Street', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R700': {name: '(Merc) Bus Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R701': {name: '(Merc) Mechanic Parking Lot', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R702': {name: '(Merc) Parking Lot Back', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R703': {name: '(Merc) Construction Site', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R704': {name: '(Merc) Energy Station Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R705': {name: '(Merc) Grill 13 Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R706': {name: '(Merc) Shopping Dist.', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R707': {name: '(Merc) Raccon City Hall Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R708': {name: '(Merc) Raccon City Hall', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R709': {name: '(Merc) Party Party Alley', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R70A': {name: '(Merc) Giant Worm Alley', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R70B': {name: '(Merc) Trolley Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R70C': {name: '(Merc) Trolley', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !0, gameEnd: !1},
			'R70D': {name: '(Merc) Stagla Gas Station', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R70E': {name: '(Merc) Stagla Street', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R70F': {name: '(Merc) Press (2F)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R710': {name: '(Merc) Press (1F)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R711': {name: '(Merc) Grill 13', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R712': {name: '(Merc) Grill 13 (B1)', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R713': {name: '(Merc) Energy Station Entrance', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R714': {name: '(Merc) Energy Station', location: 'Downtown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R718': {name: '(Merc) Fire Hose Alley', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R71A': {name: '(Merc) Parasite Alley4', location: 'Uptown', haveItemBox: !1, canSave: !1, gameStart: !1, gameEnd: !1},
			'R71B': {name: '(Merc) Mechanic\'s Office', location: 'Downtown', haveItemBox: !1, saveRoom: !1, gameStart: !1, gameEnd: !1}
		}

	}

}